# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_date', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('CL', 'Casual Leave'), ('RH', 'Restricted Holidays'), ('SCL', 'Special Casual Leave'), ('EL', 'Earned Leave'), ('COL', 'Commuted Leave')], max_length=5)),
                ('station_leave', models.BooleanField(default=False)),
                ('station_add', models.CharField(blank=True, max_length=300, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('purpose', models.CharField(default='', max_length=300)),
                ('acad_tag', models.BooleanField(default=False)),
                ('administrative_tag', models.BooleanField(default=False)),
                ('forwarding_tag', models.BooleanField(default=False)),
                ('sanctioning_tag', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('acad_duty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acad_duty', to=settings.AUTH_USER_MODEL)),
                ('administrative_duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_duty', to=settings.AUTH_USER_MODEL)),
                ('leave_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveNotifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavenotifier_type', models.CharField(choices=[('acad', 'Academic Responsibility'), ('administrative', 'Administrative Responsibility'), ('forwarding', 'Leave Forwarding'), ('sanctioning', 'Leave Sanctioning')], max_length=20)),
                ('leavenotifier_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leavenotifier_leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.Leave')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRemaining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveremaining_CL', models.IntegerField()),
                ('leaveremaining_RH', models.IntegerField()),
                ('leaveremaining_SCL', models.IntegerField()),
                ('leaveremaining_EL', models.IntegerField()),
                ('leaveremaining_COL', models.IntegerField()),
                ('leaveremaining_emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavestatus_status', models.BooleanField()),
                ('leavestatus_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leavestatus_leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.Leave')),
            ],
        ),
        migrations.CreateModel(
            name='OngoingLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ongoingleave_leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.Leave')),
            ],
        ),
    ]
