# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0002_auto_20170831_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='remarks',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('RH', 'Restricted Holidays'), ('SCL', 'Special Casual Leave'), ('EL', 'Earned Leave'), ('COL', 'Commuted Leave'), ('VL', 'Vacation Leave')], max_length=5),
        ),
    ]
