# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0003_auto_20170901_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictedHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(max_length=100)),
                ('holiday_date', models.DateField()),
            ],
        ),
    ]
